### ISSUE TITLE
Incompatibility with Replay Mod

### ISSUE THREAD

**Issue by LobbyLC** [dimadencep/RemoveReloadingScreen#45] opened 2023-08-15 15:20 UTC
### Minecraft version.

1.20.1

### Remove Reloading Screen version.

Rrls 3.1.1 for 1.20.1 (Fabric/Quilt)

### What happened?

If you attempt to render a replay shot while having a resource pack active and Rrls installed, the reloading bar will breifly appear and disappear again before loading, then the replay shot will refuse to render. You'll be stuck on the "Frames Rendered: 0/X" screen until you manually crash your game.
- This is NOT the case when no resource packs are active.
- This is NOT the case when Rrls is not installed.

https://github.com/dimadencep/RemoveReloadingScreen/assets/116382138/207263e3-dd8e-4247-87e0-080d7e237384

### Relevant log.

(No relevant log)

### Additional information.

Mods Used:
- [Cloth Config](https://modrinth.com/mod/cloth-config/version/11.1.106+fabric)
- [Fabric API](https://modrinth.com/mod/fabric-api/version/0.87.0+1.20.1)
- [Remove Reloading Screen](https://modrinth.com/mod/rrls/version/1.20.1-3.1.1-fabric)
- [Replay Mod](https://modrinth.com/mod/replaymod/version/1.20.1-2.6.13)

**Comment by dima-dencep** [comment] 2023-08-22 11:35
Have you reported this to the developers of the replaymod?

**Comment by dima-dencep** [comment] 2023-09-02 15:18
I think I know what you mean. it was pretty hard to trigger, but I don't think it's critical because after restarting replaymod offers to continue rendering

**Comment by LobbyLC** [comment] 2023-09-02 17:14
*For context, I play on a server named Wynncraft (as seen in the original clip), which is specifically where I was having this issue. I'm not sure if this can help with recreating the issue, but it may be worth a shot!*

Upon restarting my game, there's no option to continue rendering as far as I can see. It seems as though the only way I can possibly render a clip is to first disable Rrls, which is why I originally reported the issue here.

**Comment by dima-dencep** [comment] 2024-01-22 16:14
please check the latest beta

CurseForge: https://curseforge.com/minecraft/mc-mods/rrls/files/5047749 (Fabric)
Modrinth: https://modrinth.com/mod/rrls/version/4.0.0+mc1.20.4-fabric (Fabric)

CurseForge: https://curseforge.com/minecraft/mc-mods/rrls/files/5047748 (Neoforge)
Modrinth: https://modrinth.com/mod/rrls/version/4.0.0+mc1.20.4-forge (Neoforge)

**Comment by LobbyLC** [comment] 2024-01-23 03:24
This appears to have replaced one issue with another. While the replay will now render as expected, any resource packs applied by the server are removed. I've attached an example clip from the same server as before below.

Here's what should happen: (Rrls is not installed)

https://github.com/dima-dencep/rrls/assets/116382138/af32674c-aaa1-417f-a414-0424d50bde2e

Here's what is actually happening: (Rrls is installed)

https://github.com/dima-dencep/rrls/assets/116382138/dd9243b5-c14e-434f-8a9a-f2d8e2f8d1e6

**Comment by dima-dencep** [comment] 2024-01-23 04:11
Try disabling "Early sending of status about server resourcepack" option in the rrls config

If it fixes, I'll just disable it by default

**Comment by LobbyLC** [comment] 2024-01-23 05:38
The result appears to be the same as above regardless of the config.

If it helps at all, I noticed that when the server resource pack disables itself (the first time a camera path is rendered), it stays disabled even when going back to edit that camera path. The only way to get the server resource pack back is to close and re-open the Replay file.

**Comment by LobbyLC** [comment] 2024-01-23 06:00
To expand on my above comment, I also just noticed that the server resource pack won't load at all when you open a replay unless it is triggered to during gameplay.

For example, if you start recording before the server resource pack is applied, it will be applied in the replay as expected, but if the server resource pack was applied before you started recording, there will be no server resource pack in the replay at all. Again, this is not the case when Rrls is not installed and regardless of this, there is no server resource pack in the rendered replay.

I can only guess that the fix to this is forcing Rrls to check if a server resource pack is active when a replay file is opened, but I've attached an example clip below so you can take a better look:

https://github.com/dima-dencep/rrls/assets/116382138/d088c720-2b38-4319-8596-901825ccced8

(Apologies for the poor quality, GitHub has limitations, but my point should still be clear)

**Comment by dima-dencep** [comment] 2024-01-23 10:28
I want to see if anything happens in the log when there are problems with the resourcepack, send please

**Comment by dima-dencep** [comment] 2024-01-23 10:30
Rrls as far as I know doesn't do anything that would cause conflicts with replaymod, well, replaymod tries MinecraftClient#getOverlay() which I haven't changed in a while and it will get the overlay.

**Comment by LobbyLC** [comment] 2024-01-24 01:13
Here's the [latest.log](https://github.com/dima-dencep/rrls/files/14031348/latest.log) - hopefully this is the log you were asking for before, but let me know if it's not. To confirm, I opened Minecraft, rendered the replay, then closed Minecraft again so it shouldn't be cluttered with any unnecessary info.

**Comment by dima-dencep** [comment] 2024-01-25 16:58
I don't understand why this bug happens, replaymod updates the textures after the reload is complete?

**Comment by dima-dencep** [comment] 2024-01-26 10:57
Try:
> CurseForge: https://curseforge.com/minecraft/mc-mods/rrls/files/5060605 (Fabric)
> Modrinth: https://modrinth.com/mod/rrls/version/4.0.1+mc1.20.4-fabric (Fabric)
>
> CurseForge: https://curseforge.com/minecraft/mc-mods/rrls/files/5060604 (Neoforge)
> Modrinth: https://modrinth.com/mod/rrls/version/4.0.1+mc1.20.4-forge (Neoforge)

And enable "Complete blocking of overlay usage" in the rrls config

**Comment by LobbyLC** [comment] 2024-01-28 12:40
Apologies for the late response. This update doesn't seem to change anything, the result is the same as my previous example video - still no server resource pack.

**Comment by dima-dencep** [comment] 2024-04-22 19:03
Fixed in 4.0.3 (I can't reproduce it anymore)

**Closed as completed by dima-dencep** 2024-04-22 19:03 UTC
Labels: bug
